AddressBook/Address Book/Models/AddressBookViewModel.cs
namespace Address_Book.Models
{
    public class AddressBookViewModel
    {
        public int Id { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
    }
}

AddressBook/Address Book/Models/ErrorViewModel.cs
namespace Address_Book.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

AddressBook/Address Book/Controllers/AddressBookController.cs
using Microsoft.AspNetCore.Mvc;
using Address_Book.Models;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.IO;
using System.Runtime.Serialization.Json;
using System.Reflection;


namespace Address_Book.Controllers
{

    public class AddressBookController : Controller
    {
        /// <summary>
        /// A List of objects of the model
        /// </summary>
        List<AddressBookViewModel> models = new List<AddressBookViewModel>();
        JSONReadWrite readWrite = new JSONReadWrite();
        /// <summary>
        /// Constructor that give id to each of the person, and deserialize the json file data
        /// </summary>
        public AddressBookController()
        {
            giveID(models);
            models = JsonConvert.DeserializeObject<List<AddressBookViewModel>>(readWrite.Read("addressbook.json", "data"));
        }
        /// <summary>
        /// A function to give Id to each of the person in json file data
        /// </summary>
        /// <param name="models"></param>
        public void giveID(List<AddressBookViewModel> models)
        {
            int idCount = 1;
            models = JsonConvert.DeserializeObject<List<AddressBookViewModel>>(readWrite.Read("addressbook.json", "data"));
            foreach (var m in models)
            {
                m.Id = idCount;
                idCount = idCount + 1;
            }
            string jSONString = JsonConvert.SerializeObject(models);
            readWrite.Write("addressbook.json", "data", jSONString);
        }
        public IActionResult Index()
        {
            return View(models);
        }

        public IActionResult Add()
        {
            return View();
        }
        /// <summary>
        /// Function to add the data, from input form, and write it to json file
        /// </summary>
        /// <param name="addressBookViewModel"></param>
        /// <returns></returns>
        public IActionResult AddAddress(AddressBookViewModel addressBookViewModel)
        {
            models = JsonConvert.DeserializeObject<List<AddressBookViewModel>>(readWrite.Read("addressbook.json", "data"));
            models.Add(addressBookViewModel);
            string jSONString = JsonConvert.SerializeObject(models);
            readWrite.Write("addressbook.json", "data", jSONString);
            return RedirectToAction("Index");
        }
        /// <summary>
        /// Function to Delete the record, when the button is pressed. First delete it from the list, then rewrite the json file
        /// </summary>
        /// <param name="id2del"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Delete(int id2del)
        {
            models.RemoveAt(id2del - 1);
            giveID(models);
            string jSONString = JsonConvert.SerializeObject(models);
            readWrite.Write("addressbook.json", "data", jSONString);
            return RedirectToAction("Index");
        }
        public ActionResult Edit(int id)
        {
            var model = models.FirstOrDefault(m => m.Id == id);
            return View(model);
        }
        /// <summary>
        /// Function to Edit the existing data, when the button is pressed, then rewrite the new data into json file when button is submitted
        /// </summary>
        /// <param name="model"></param>
        /// <returns> return to index page </returns>
        [HttpPost]
        public ActionResult Edit(AddressBookViewModel model)
        {
            var existingModel = models.FirstOrDefault(m => m.Id == model.Id);
            existingModel.first_name = model.first_name;
            existingModel.last_name = model.last_name;
            existingModel.phone = model.phone;
            existingModel.email = model.email;
            string jSONString = JsonConvert.SerializeObject(models);
            readWrite.Write("addressbook.json", "data", jSONString);
            return RedirectToAction("Index");
        }

        public int getLength()
        {
            return models.Count(); 
        }
    }

    public class JSONReadWrite
    {
        /// <summary>
        /// Read Json File
        /// </summary>
        public JSONReadWrite() { }

        public string Read(string fileName, string location)
        {
            string root = "wwwroot";
            var path = Path.Combine(
                Directory.GetCurrentDirectory(),
                root,
                location,
                fileName);

            string jsonResult;

            using (StreamReader streamReader = new StreamReader(path))
            {
                jsonResult = streamReader.ReadToEnd();
            }
            return jsonResult;
        }
        /// <summary>
        /// ReWrite text into Json File
        /// </summary>

        public void Write(string fileName, string location, string jSONString)
        {
            string root = "wwwroot";
            var path = Path.Combine(
                Directory.GetCurrentDirectory(),
                root,
                location,
                fileName);

            using (var streamWriter = File.CreateText(path))
            {
                streamWriter.Write(jSONString);
            }
        }
    }
}

AddressBook/Address Book/Controllers/Api/ValuesController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Address_Book.Controllers.Api
{
    [Route("api/[controller]")]
    [ApiController]
    public class ValuesController : ControllerBase
    {
    }
}

AddressBook/Address Book/Views/AddressBook/Add.cshtml
@model AddressBookViewModel

<h1>Add your addresses here</h1>

<div class="row">
    <div class="col-12">


        <div class="card">
            <div class="card-header">
            </div>

            <div class="card-body">
                <form asp-controller="AddressBook" asp-action="AddAddress" method="post">
                    <div>
                        <label class="form-label">First Name</label>
                        <input asp-for=first_name type="text" class="form-control" />
                    </div>

                    <div>
                        <label class="form-label">Last Name</label>
                        <input asp-for=last_name type="text" class="form-control" />
                    </div>

                    <div>
                        <label class="form-label">Email Address</label>
                        <input asp-for=email type="text" class="form-control" />
                    </div>

                    <div>
                        <label class="form-label">Phone No.</label>
                        <input asp-for=phone type="text" class="form-control" />
                    </div>

                    <hr />

                    <div class="mb-3">
                        <button type="submit" class="btn btn-primary">Save</button>
                        <button type="reset" class="btn btn-primary">Clear</button>
                    </div>
                </form>
            </div>


            <div class="card-footer">
            </div>


        </div>

    </div>
</div>

AddressBook/Address Book/Views/AddressBook/Edit.cshtml
@model AddressBookViewModel
<h1>Edit @Model.first_name @Model.last_name's information here</h1>

<div class="row">
    <div class="col-12">


        <div class="card">
            <div class="card-header">
            </div>


            <div class="card-body">
                @using (Html.BeginForm("Edit", "AddressBook", FormMethod.Post))
                {
                    <div class="mb-3">
                        @Html.LabelFor(m => m.first_name, "First Name")
                        @Html.TextBoxFor(m => m.first_name, new { @class = "form-control" })
                    </div>
                    <div class="mb-3">
                        @Html.LabelFor(m => m.last_name, "Last Name")
                        @Html.TextBoxFor(m => m.last_name, new { @class = "form-control" })
                    </div>
                    <div class="mb-3">
                        @Html.LabelFor(m => m.phone, "Phone")
                        @Html.TextBoxFor(m => m.phone, new { @class = "form-control" })
                    </div>
                    <div class="mb-3">
                        @Html.LabelFor(m => m.email, "Email")
                        @Html.TextBoxFor(m => m.email, new { @class = "form-control" })
                    </div>
                    <div class="mb-3">
                        <input class="btn btn-success" type="submit" value="Save" />
                    </div>
                }
                <hr />


            </div>


            <div class="card-footer">
            </div>


        </div>

    </div>
</div>

AddressBook/Address Book/Views/AddressBook/Index.cshtml
@model List<Address_Book.Models.AddressBookViewModel>

<h1>View addresses here</h1>
@foreach (var item in Model)
{
    @using (Html.BeginForm("Delete", "AddressBook", FormMethod.Post))
    {
        <h3>@item.first_name @item.last_name</h3>
        <p>@item.phone</p>
        <p>@item.email</p>
        <div class="button-container" style="display: flex; width: 10%; justify-content: space-between">
            <input type="hidden" name="id2del" value="@item.Id" />
            <input type="submit" value="Delete" class="btn btn-danger" onclick="return confirm ('Are you sure to delete record with @item.first_name @item.last_name');" />
            <input type="button" value="Edit" class="btn btn-warning" onclick="location.href='@Url.Action("Edit", "AddressBook", new { id = item.Id })'" />
        </div>
        <hr />
    }
}

AddressBook/Address Book/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Address_Book</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Address_Book.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Address Book</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="AddressBook" asp-action="Index">Show all addresses</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="AddressBook" asp-action="Add">Add address</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Address_Book - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>